/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  ManufacturerOnboarding: () => import('#controllers/manufacturer_onboarding_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  OfferActions: () => import('#controllers/offer_actions_controller'),
  Panel: () => import('#controllers/panel_controller'),
  ProductionRequestsApi: () => import('#controllers/production_requests_api_controller'),
  ProductionSteps: () => import('#controllers/production_steps_controller'),
  RegionCapability: () => import('#controllers/region_capability_controller'),
  Session: () => import('#controllers/session_controller'),
  WebhookEventsApi: () => import('#controllers/webhook_events_api_controller'),
}
