/**
 * Readable names for form fields in validation messages: "The address field is required", not
 * "The line1 field…". Keyed by the property name (VineJS looks it up at any depth). Single plain
 * words (email, city, title…) read fine as they are and are left out. The Turkish names, keyed by
 * these labels, live in services/i18n/validation_messages.ts.
 */
export const FIELD_LABELS: Record<string, string> = {
  line1: 'address',
  line2: 'address line 2',
  postalCode: 'postal code',
  fullName: 'full name',
  passwordConfirmation: 'password confirmation',
  currentPassword: 'current password',
  businessName: 'business name',
  identityNumber: 'ID number',
  taxId: 'tax number',
  isCorporate: 'company account',
  acceptTerms: 'terms',
  couponCode: 'coupon code',
  trackingNumber: 'tracking number',
  shipCountry: 'delivery country',
  shippingAddress: 'delivery address',
  minOrder: 'minimum order',
  maxDiscount: 'maximum discount',
  maxRedemptions: 'usage limit',
  perUserLimit: 'limit per customer',
  firstOrderOnly: 'first order only',
  minPrice: 'minimum price',
  maxPrice: 'maximum price',
  pricePerGramMinor: 'price per gram',
  materialCostPerKgMinor: 'material cost per kg',
  refundMinor: 'refund amount',
  commissionPercent: 'commission',
  multiplierPercent: 'multiplier',
  marginBps: 'margin',
  scalePercent: 'scale',
  bidDays: 'delivery days',
  leadDays: 'lead time',
  maxLeadDays: 'maximum lead time',
  extraDays: 'extra days',
  maxMinutes: 'maximum minutes',
  endsAt: 'end date',
  buildVolumeXMm: 'build width',
  buildVolumeYMm: 'build depth',
  buildVolumeZMm: 'build height',
  allowedMaterials: 'materials',
  allowedScales: 'scales',
  finishingColour: 'finishing colour',
  printerModelId: 'printer model',
  printProfileId: 'print profile',
  catalogProductId: 'product',
  categoryId: 'category',
  modelFileId: 'model file',
  manufacturerProfileId: 'maker',
  replacesFileId: 'file',
  optionIds: 'options',
  profileIds: 'makers',
  bidId: 'offer',
  minMakerTier: 'minimum maker tier',
  requiredTrustTier: 'required trust tier',
  isActive: 'active',
  originalName: 'file name',
  sizeBytes: 'file size',
  contentType: 'file type',
  storageKey: 'file',
  cvc: 'security code',
  expiry: 'expiry date',
  number: 'card number',
}
