export interface SettingDefinition {
  key: string
  group:
    | 'pricing'
    | 'makerPay'
    | 'matching'
    | 'orders'
    | 'trust'
    | 'fraud'
    | 'flags'
    | 'referral'
    | 'payouts'
  label: string
  help: string
  /**
   * How the admin screen shows and takes the value; it is always stored as the number below.
   * percent: stored in basis points, typed as a percent (2500 → 25 %). money: stored in TRY minor
   * units, typed in lira. toggle: 0 = off, 1 = on. choice: one of `choices`. Default: number.
   */
  kind?: 'number' | 'percent' | 'money' | 'toggle' | 'choice'
  choices?: Array<{ value: number; label: string }>
  min: number
  max: number
  integer: boolean
}

/** Every admin-editable knob. `config/fabrmatch.ts` only holds the defaults. */
export const SETTING_DEFINITIONS: SettingDefinition[] = [
  {
    key: 'pricing.commissionBps',
    kind: 'percent',
    group: 'pricing',
    label: 'Platform commission',
    help: 'Applies to new quotes only; orders already priced keep their fee.',
    min: 0,
    max: 5000,
    integer: true,
  },
  {
    key: 'pricing.fxMarginBps',
    kind: 'percent',
    group: 'pricing',
    label: 'Foreign-currency buffer',
    help: 'Added once on top of the mid rate when a buyer pays in USD, EUR or GBP, and booked as FX gain. A region can set its own.',
    min: 0,
    max: 2000,
    integer: true,
  },
  {
    key: 'pricing.extraColourMinor',
    kind: 'money',
    group: 'pricing',
    label: 'Extra colour fee (per piece)',
    help: 'Added for each colour after the first in a multi-colour print. It goes to the maker (filament changes and purge waste) and applies to new orders only.',
    min: 0,
    max: 100_000,
    integer: true,
  },
  {
    key: 'pricing.fxMaxAgeHours',
    group: 'pricing',
    label: 'Exchange rate: longest age (hours)',
    help: 'Orders in a foreign currency are refused when the stored rate is older than this.',
    min: 1,
    max: 720,
    integer: true,
  },
  {
    key: 'makerPay.minProfitBps',
    group: 'makerPay',
    kind: 'percent',
    label: 'Maker profit: minimum',
    help: 'Every maker earns at least this on top of their own costs. Makers can raise their own profit up to the maximum below.',
    min: 0,
    max: 10_000,
    integer: true,
  },
  {
    key: 'makerPay.maxProfitBps',
    group: 'makerPay',
    kind: 'percent',
    label: 'Maker profit: maximum',
    help: 'The highest profit a maker can choose. A higher profit means fewer orders fit their price.',
    min: 0,
    max: 10_000,
    integer: true,
  },
  {
    key: 'makerPay.referenceHourlyRateMinor',
    group: 'makerPay',
    kind: 'money',
    label: 'Reference maker: machine hour',
    help: 'Power, wear and paying off the printer, per print hour. Prices use the reference maker until makers enter their own costs.',
    min: 0,
    max: 1_000_000,
    integer: true,
  },
  {
    key: 'makerPay.referenceSetupMinor',
    group: 'makerPay',
    kind: 'money',
    label: 'Reference maker: setup per print job',
    help: 'Preparing the print, removing supports and packing, once per order line.',
    min: 0,
    max: 1_000_000,
    integer: true,
  },
  {
    key: 'makerPay.referenceWasteBps',
    group: 'makerPay',
    kind: 'percent',
    label: 'Reference maker: material waste',
    help: 'Extra material lost to purging, brims and supports.',
    min: 0,
    max: 5000,
    integer: true,
  },
  {
    key: 'makerPay.referenceFailureBps',
    group: 'makerPay',
    kind: 'percent',
    label: 'Reference maker: failed prints',
    help: 'Share of prints that fail and are printed again; the cost is spread over the good ones.',
    min: 0,
    max: 5000,
    integer: true,
  },
  {
    key: 'makerPay.maxDistanceBps',
    group: 'makerPay',
    kind: 'percent',
    label: 'Maker distance surcharge: maximum',
    help: 'The most a maker may add to their price for an order delivered to another city. Their nearer orders stay cheaper.',
    min: 0,
    max: 10_000,
    integer: true,
  },
  {
    key: 'makerPay.quoteCoverageBps',
    group: 'makerPay',
    kind: 'percent',
    label: 'Fixed price: makers it pays enough',
    help: 'The price the buyer pays is set so that this share of the makers who could print the order earn their own price or more. Higher: more makers can take it, buyers pay a little more.',
    min: 1000,
    max: 10_000,
    integer: true,
  },
  {
    key: 'makerPay.quoteRangeLowBps',
    group: 'makerPay',
    kind: 'percent',
    label: 'Price range: low end',
    help: 'The instant quote shows a range; its low end is the makers’ price at this point of the market (20% = cheaper than four in five).',
    min: 0,
    max: 10_000,
    integer: true,
  },
  {
    key: 'makerPay.quoteRangeHighBps',
    group: 'makerPay',
    kind: 'percent',
    label: 'Price range: high end',
    help: 'The high end of the range. The fixed price always sits inside the range.',
    min: 0,
    max: 10_000,
    integer: true,
  },
  {
    key: 'makerPay.quoteMinMakers',
    group: 'makerPay',
    label: 'Fewest makers for a market price',
    help: 'With fewer makers able to print an order, it is priced at the reference maker, raised up to the band below for a dearer one.',
    min: 1,
    max: 50,
    integer: true,
  },
  {
    key: 'makerPay.quoteFallbackBandBps',
    group: 'makerPay',
    kind: 'percent',
    label: 'Price range with few makers',
    help: 'Without a market, the range runs from the price to this much above it.',
    min: 0,
    max: 10_000,
    integer: true,
  },
  {
    key: 'matching.autoOffer',
    kind: 'toggle',
    group: 'matching',
    label: 'Automatic matching',
    help: 'Off: every paid order waits in Matching until an admin picks the maker. On: offers go out by score.',
    min: 0,
    max: 1,
    integer: true,
  },
  {
    key: 'matching.explorationRate',
    group: 'matching',
    label: 'New-maker discovery share',
    help: '0.2 = one offer in five goes to a new maker. 0 disables discovery.',
    min: 0,
    max: 1,
    integer: false,
  },
  {
    key: 'matching.offerTtlMinutes',
    group: 'matching',
    label: 'Offer lifetime (minutes)',
    help: 'How long a maker has to accept before the offer moves on.',
    min: 5,
    max: 1440,
    integer: true,
  },
  {
    key: 'matching.counterOffers',
    group: 'matching',
    kind: 'toggle',
    label: 'Counter-offers',
    help: 'On: a maker who finds an offer too low can ask for more, up to what the order pays makers. An admin approves or declines.',
    min: 0,
    max: 1,
    integer: true,
  },
  {
    key: 'matching.counterTtlMinutes',
    group: 'matching',
    label: 'Counter-offer answer time (minutes)',
    help: 'Without an answer by then, the counter-offer lapses and the next maker is tried.',
    min: 10,
    max: 2880,
    integer: true,
  },
  {
    key: 'matching.revisionTtlMinutes',
    group: 'matching',
    label: 'Revision answer time (minutes)',
    help: 'How long a buyer has to answer when a maker asks for a change. Without an answer the next maker is tried.',
    min: 60,
    max: 10_080,
    integer: true,
  },
  {
    key: 'matching.maxRounds',
    group: 'matching',
    label: 'Matching rounds before "unmatched"',
    help: 'Offers tried in sequence before the order is marked unmatched.',
    min: 1,
    max: 20,
    integer: true,
  },
  {
    key: 'orders.productionSlaDays',
    group: 'orders',
    label: 'Production deadline (days)',
    help: 'Time a maker has from acceptance to ship.',
    min: 1,
    max: 30,
    integer: true,
  },
  {
    key: 'orders.autoDeliverDaysAfterShip',
    group: 'orders',
    label: 'Assume delivered after shipping (days)',
    help: 'Used while there is no carrier tracking integration.',
    min: 3,
    max: 60,
    integer: true,
  },
  {
    key: 'orders.autoConfirmDays',
    group: 'orders',
    label: 'Buyer confirmation / dispute window (days)',
    help: 'After delivery the buyer can open a dispute; then the order completes automatically.',
    min: 1,
    max: 30,
    integer: true,
  },
  {
    key: 'orders.shopWaitingNoticeHours',
    group: 'orders',
    label: 'Tell the seller a shop order waits for a maker after (hours)',
    help: 'An order from a seller’s own shop that no maker has taken by then: the seller hears it once, so they can answer their customer.',
    min: 1,
    max: 336,
    integer: true,
  },
  {
    key: 'orders.unmatchedAutoCancelDays',
    group: 'orders',
    label: 'Cancel unmatched orders after (days)',
    help: 'Paid but nobody accepted: cancelled and refunded automatically.',
    min: 1,
    max: 30,
    integer: true,
  },
  {
    key: 'trust.tier1MinJobs',
    group: 'trust',
    label: 'Verified tier: completed jobs',
    help: 'Delivered jobs a maker needs before reaching tier 1.',
    min: 1,
    max: 200,
    integer: true,
  },
  {
    key: 'trust.tier1MaxDisputePercent',
    group: 'trust',
    label: 'Verified tier: max dispute rate (%)',
    help: 'Share of jobs that ended in a dispute must stay below this.',
    min: 0,
    max: 50,
    integer: true,
  },
  {
    key: 'trust.tier2MinJobs',
    group: 'trust',
    label: 'Trusted tier: completed jobs',
    help: 'Delivered jobs needed for tier 2 (longer, unlimited file access).',
    min: 5,
    max: 1000,
    integer: true,
  },
  {
    key: 'trust.tier2MinRating',
    group: 'trust',
    label: 'Trusted tier: average rating',
    help: 'Buyer rating (1–5) needed for tier 2.',
    min: 1,
    max: 5,
    integer: false,
  },
  {
    key: 'trust.tier0MaxOrderMinor',
    kind: 'money',
    group: 'trust',
    label: 'New makers: largest order',
    help: 'Bigger orders wait for a verified maker.',
    min: 1000,
    max: 1_000_000_000,
    integer: true,
  },
  {
    key: 'trust.tier1MaxOrderMinor',
    kind: 'money',
    group: 'trust',
    label: 'Verified makers: largest order',
    help: 'Orders above this need a trusted (tier 2) maker.',
    min: 1000,
    max: 1_000_000_000,
    integer: true,
  },
  {
    key: 'trust.tier2MaxOrderMinor',
    kind: 'money',
    group: 'trust',
    label: 'Trusted makers: largest order',
    help: 'Orders above this go to partners (tier 3) only.',
    min: 1000,
    max: 1_000_000_000,
    integer: true,
  },
  {
    key: 'fraud.newAccountHours',
    group: 'fraud',
    label: 'New account window (hours)',
    help: 'Accounts younger than this are "new" for the high-value rule.',
    min: 1,
    max: 720,
    integer: true,
  },
  {
    key: 'fraud.newAccountMaxOrderMinor',
    kind: 'money',
    group: 'fraud',
    label: 'New account: largest order without review',
    help: 'Bigger orders from a new account wait for manual review before matching.',
    min: 1000,
    max: 1_000_000_000,
    integer: true,
  },
  {
    key: 'fraud.ordersPerHour',
    group: 'fraud',
    label: 'Orders per hour before a review flag',
    help: 'One buyer paying for this many orders in an hour is flagged.',
    min: 2,
    max: 100,
    integer: true,
  },
  {
    key: 'flags.externalStores',
    kind: 'toggle',
    group: 'flags',
    label: 'Feature: shop integrations (Shopify, Etsy, WooCommerce, Wix)',
    help: 'On shows the feature, off hides it everywhere.',
    min: 0,
    max: 1,
    integer: true,
  },
  {
    key: 'flags.rfq',
    kind: 'toggle',
    group: 'flags',
    label: 'Feature: quote requests (RFQ)',
    help: 'On shows the feature, off hides it everywhere.',
    min: 0,
    max: 1,
    integer: true,
  },
  {
    key: 'flags.crossBorder',
    kind: 'toggle',
    group: 'flags',
    label: 'Feature: cross-border orders',
    help: 'On shows the feature, off hides it everywhere.',
    min: 0,
    max: 1,
    integer: true,
  },
  {
    key: 'flags.currencyUsd',
    kind: 'toggle',
    group: 'flags',
    label: 'Feature: pay in USD',
    help: 'Lets buyers pay in USD. Only turn on when the payment provider settles it.',
    min: 0,
    max: 1,
    integer: true,
  },
  {
    key: 'flags.currencyEur',
    kind: 'toggle',
    group: 'flags',
    label: 'Feature: pay in EUR',
    help: 'Lets buyers pay in EUR. Only turn on when the payment provider settles it.',
    min: 0,
    max: 1,
    integer: true,
  },
  {
    key: 'flags.currencyGbp',
    kind: 'toggle',
    group: 'flags',
    label: 'Feature: pay in GBP',
    help: 'Lets buyers pay in GBP. Only turn on when the payment provider settles it.',
    min: 0,
    max: 1,
    integer: true,
  },
  {
    key: 'referral.rewardMinor',
    kind: 'money',
    group: 'referral',
    label: 'Invite reward per person',
    help: 'A coupon of this amount for the friend and for the member who invited them. The platform fee of the order still caps the discount.',
    min: 100,
    max: 1_000_000,
    integer: true,
  },
  {
    key: 'referral.minOrderMinor',
    kind: 'money',
    group: 'referral',
    label: 'Invite reward: friend’s first order at least',
    help: 'Rewards are paid only when the friend’s first completed order reaches this total.',
    min: 0,
    max: 10_000_000,
    integer: true,
  },
  {
    key: 'referral.maxRewards',
    group: 'referral',
    label: 'Invite rewards one member can earn',
    help: 'Stops farming: after this many rewards the member can still invite, but earns no more.',
    min: 1,
    max: 1000,
    integer: true,
  },
  {
    key: 'referral.couponDays',
    group: 'referral',
    label: 'Reward coupon lifetime (days)',
    help: 'How long a reward coupon stays valid after it is issued.',
    min: 7,
    max: 730,
    integer: true,
  },
  {
    key: 'flags.referrals',
    kind: 'toggle',
    group: 'flags',
    label: 'Feature: invite a friend',
    help: 'Turns the program on. Publish the terms first.',
    min: 0,
    max: 1,
    integer: true,
  },
  {
    key: 'payouts.homeExemptWithholdingBps',
    kind: 'percent',
    group: 'payouts',
    label: 'Withholding on home producers',
    help: 'Income tax Fabrmatch withholds on the expense voucher of a maker with the home-production exemption (GVK 94/13). Confirm the rate with the accountant.',
    min: 0,
    max: 2000,
    integer: true,
  },
  {
    key: 'payouts.homeExemptAnnualCapMinor',
    kind: 'money',
    group: 'payouts',
    label: 'Home-production exemption: yearly limit',
    help: 'The 2026 limit under GVK 9/6. Payouts that would take a home producer past it this calendar year stop and wait for an admin.',
    min: 0,
    max: 2_000_000_000,
    integer: true,
  },
]

export const SETTING_KEYS = SETTING_DEFINITIONS.map((d) => d.key)
