/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ApiKeySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'keyHash', 'lastUsedAt', 'name', 'prefix', 'revokedAt', 'userId'] as const
  $columns = ApiKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare keyHash: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare prefix: string
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare userId: number
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'actorId', 'createdAt', 'id', 'meta', 'subjectId', 'subjectType'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare meta: any
  @column()
  declare subjectId: number
  @column()
  declare subjectType: string
}

export class CapacitySlotSchema extends BaseModel {
  static $columns = ['createdAt', 'date', 'id', 'maxMinutes', 'printerId', 'reservedMinutes', 'updatedAt'] as const
  $columns = CapacitySlotSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maxMinutes: number
  @column()
  declare printerId: number
  @column()
  declare reservedMinutes: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CarrierEventSchema extends BaseModel {
  static $columns = ['eventId', 'id', 'processedAt', 'provider', 'receivedAt', 'status', 'trackingNumber'] as const
  $columns = CarrierEventSchema.$columns
  @column()
  declare eventId: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare processedAt: DateTime | null
  @column()
  declare provider: string
  @column.dateTime()
  declare receivedAt: DateTime
  @column()
  declare status: string
  @column()
  declare trackingNumber: string
}

export class CartItemSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'finishingCode', 'finishingColour', 'id', 'infill', 'material', 'modelFileId', 'printProfileId', 'quantity', 'updatedAt', 'userId'] as const
  $columns = CartItemSchema.$columns
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare finishingCode: string | null
  @column()
  declare finishingColour: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare infill: string | null
  @column()
  declare material: string
  @column()
  declare modelFileId: number
  @column()
  declare printProfileId: number | null
  @column()
  declare quantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class CatalogProductSchema extends BaseModel {
  static $columns = ['allowedMaterials', 'allowedScales', 'categoryId', 'createdAt', 'description', 'id', 'isActive', 'modelFileId', 'slug', 'tags', 'title', 'updatedAt'] as const
  $columns = CatalogProductSchema.$columns
  @column()
  declare allowedMaterials: any
  @column()
  declare allowedScales: any
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare modelFileId: number | null
  @column()
  declare slug: string
  @column()
  declare tags: any
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isActive', 'name', 'slug'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare slug: string
}

export class ChargebackSchema extends BaseModel {
  static $columns = ['amountMinor', 'createdAt', 'currency', 'id', 'note', 'orderId', 'paymentId', 'providerEventId', 'resolvedAt', 'resolvedBy', 'status', 'writtenOffMinor'] as const
  $columns = ChargebackSchema.$columns
  @column()
  declare amountMinor: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string | null
  @column()
  declare orderId: number
  @column()
  declare paymentId: number
  @column()
  declare providerEventId: string
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare resolvedBy: number | null
  @column()
  declare status: string
  @column()
  declare writtenOffMinor: number
}

export class ColorSchema extends BaseModel {
  static $columns = ['createdAt', 'hex', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = ColorSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare hex: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ConsentSchema extends BaseModel {
  static $columns = ['createdAt', 'granted', 'id', 'kind', 'userId', 'version'] as const
  $columns = ConsentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare granted: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare userId: number
  @column()
  declare version: string
}

export class ContentReportSchema extends BaseModel {
  static $columns = ['createdAt', 'details', 'id', 'modelFileId', 'reason', 'reporterId', 'resolvedAt', 'resolvedBy', 'sellerProductId', 'status'] as const
  $columns = ContentReportSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare details: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare modelFileId: number | null
  @column()
  declare reason: string
  @column()
  declare reporterId: number
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare resolvedBy: number | null
  @column()
  declare sellerProductId: number | null
  @column()
  declare status: string
}

export class CouponRedemptionSchema extends BaseModel {
  static $columns = ['couponId', 'createdAt', 'discountMinor', 'id', 'orderId', 'userId'] as const
  $columns = CouponRedemptionSchema.$columns
  @column()
  declare couponId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare discountMinor: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number
  @column()
  declare userId: number
}

export class CouponSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'endsAt', 'firstOrderOnly', 'id', 'isActive', 'kind', 'maxDiscountMinor', 'maxRedemptions', 'minOrderMinor', 'note', 'perUserLimit', 'startsAt', 'userId', 'value'] as const
  $columns = CouponSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare endsAt: DateTime | null
  @column()
  declare firstOrderOnly: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare kind: string
  @column()
  declare maxDiscountMinor: number | null
  @column()
  declare maxRedemptions: number | null
  @column()
  declare minOrderMinor: number
  @column()
  declare note: string | null
  @column()
  declare perUserLimit: number
  @column.dateTime()
  declare startsAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare value: number
}

export class DisputeEvidenceSchema extends BaseModel {
  static $columns = ['createdAt', 'disputeId', 'id', 'note', 'storageKey', 'uploaderId'] as const
  $columns = DisputeEvidenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare disputeId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string | null
  @column()
  declare storageKey: string
  @column()
  declare uploaderId: number
}

export class DisputeSchema extends BaseModel {
  static $columns = ['adminNote', 'createdAt', 'id', 'manufacturerResponse', 'openedBy', 'orderId', 'reason', 'refundMinor', 'resolution', 'resolvedAt', 'resolvedBy', 'status', 'updatedAt'] as const
  $columns = DisputeSchema.$columns
  @column()
  declare adminNote: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare manufacturerResponse: string | null
  @column()
  declare openedBy: number
  @column()
  declare orderId: number
  @column()
  declare reason: string
  @column()
  declare refundMinor: number
  @column()
  declare resolution: string | null
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare resolvedBy: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ExperimentEventSchema extends BaseModel {
  static $columns = ['createdAt', 'event', 'experiment', 'id', 'variant', 'visitorHash'] as const
  $columns = ExperimentEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare event: string
  @column()
  declare experiment: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare variant: string
  @column()
  declare visitorHash: string
}

export class ExternalListingSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'externalProductId', 'externalVariantId', 'id', 'material', 'priceMinor', 'published', 'scalePercent', 'sellerProductId', 'sku', 'storeConnectionId', 'title', 'updatedAt'] as const
  $columns = ExternalListingSchema.$columns
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalProductId: string
  @column()
  declare externalVariantId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare material: string | null
  @column()
  declare priceMinor: number | null
  @column()
  declare published: boolean
  @column()
  declare scalePercent: number | null
  @column()
  declare sellerProductId: number | null
  @column()
  declare sku: string | null
  @column()
  declare storeConnectionId: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ExternalOrderSchema extends BaseModel {
  static $columns = ['createdAt', 'error', 'externalOrderId', 'externalOrderName', 'fulfillmentAttempts', 'fulfillmentError', 'fulfillmentPushedAt', 'fulfillmentStatus', 'id', 'lines', 'orderId', 'shippingAddressEnc', 'shopCancelledAt', 'status', 'storeConnectionId', 'updatedAt'] as const
  $columns = ExternalOrderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare error: string | null
  @column()
  declare externalOrderId: string
  @column()
  declare externalOrderName: string | null
  @column()
  declare fulfillmentAttempts: number
  @column()
  declare fulfillmentError: string | null
  @column.dateTime()
  declare fulfillmentPushedAt: DateTime | null
  @column()
  declare fulfillmentStatus: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lines: any
  @column()
  declare orderId: number | null
  @column()
  declare shippingAddressEnc: string
  @column.dateTime()
  declare shopCancelledAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare storeConnectionId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FileAccessGrantSchema extends BaseModel {
  static $columns = ['createdAt', 'downloadCount', 'expiresAt', 'id', 'manufacturerProfileId', 'maxDownloads', 'modelFileId', 'productionJobId', 'updatedAt'] as const
  $columns = FileAccessGrantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare downloadCount: number
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare manufacturerProfileId: number
  @column()
  declare maxDownloads: number
  @column()
  declare modelFileId: number
  @column()
  declare productionJobId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FileDownloadLogSchema extends BaseModel {
  static $columns = ['createdAt', 'grantId', 'id', 'ipAddress', 'manufacturerProfileId', 'userAgent'] as const
  $columns = FileDownloadLogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare grantId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare manufacturerProfileId: number
  @column()
  declare userAgent: string | null
}

export class FinishingOptionSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'description', 'extraDays', 'id', 'isActive', 'materials', 'name', 'needsColour', 'priceMinor'] as const
  $columns = FinishingOptionSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare extraDays: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare materials: any | null
  @column()
  declare name: string
  @column()
  declare needsColour: boolean
  @column()
  declare priceMinor: number
}

export class FraudFlagSchema extends BaseModel {
  static $columns = ['createdAt', 'detail', 'id', 'orderId', 'resolvedAt', 'resolvedBy', 'rule', 'severity', 'status'] as const
  $columns = FraudFlagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare detail: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare resolvedBy: number | null
  @column()
  declare rule: string
  @column()
  declare severity: string
  @column()
  declare status: string
}

export class FxRateSchema extends BaseModel {
  static $columns = ['asOf', 'createdAt', 'currency', 'id', 'rateNano', 'source'] as const
  $columns = FxRateSchema.$columns
  @column.date()
  declare asOf: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rateNano: bigint | number
  @column()
  declare source: string
}

export class InvoiceCounterSchema extends BaseModel {
  static $columns = ['lastNumber', 'year'] as const
  $columns = InvoiceCounterSchema.$columns
  @column()
  declare lastNumber: number
  @column({ isPrimary: true })
  declare year: number
}

export class InvoiceSchema extends BaseModel {
  static $columns = ['currency', 'grossMinor', 'id', 'issuedAt', 'kind', 'netMinor', 'number', 'orderId', 'provider', 'providerRef', 'recipientUserId', 'status', 'taxMinor', 'taxRateBps'] as const
  $columns = InvoiceSchema.$columns
  @column()
  declare currency: string
  @column()
  declare grossMinor: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare issuedAt: DateTime
  @column()
  declare kind: string
  @column()
  declare netMinor: number
  @column()
  declare number: string
  @column()
  declare orderId: number
  @column()
  declare provider: string
  @column()
  declare providerRef: string | null
  @column()
  declare recipientUserId: number
  @column()
  declare status: string
  @column()
  declare taxMinor: number
  @column()
  declare taxRateBps: number
}

export class JobQcPhotoSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'productionJobId', 'storageKey'] as const
  $columns = JobQcPhotoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productionJobId: number
  @column()
  declare storageKey: string
}

export class LeadSchema extends BaseModel {
  static $columns = ['city', 'consentAt', 'consentVersion', 'createdAt', 'email', 'id', 'interest', 'referrerHost', 'utmCampaign', 'utmMedium', 'utmSource'] as const
  $columns = LeadSchema.$columns
  @column()
  declare city: string | null
  @column.dateTime()
  declare consentAt: DateTime
  @column()
  declare consentVersion: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare interest: string
  @column()
  declare referrerHost: string | null
  @column()
  declare utmCampaign: string | null
  @column()
  declare utmMedium: string | null
  @column()
  declare utmSource: string | null
}

export class LedgerEntrySchema extends BaseModel {
  static $columns = ['account', 'amountMinor', 'createdAt', 'currency', 'direction', 'id', 'memo', 'orderId', 'transactionId', 'walletUserId'] as const
  $columns = LedgerEntrySchema.$columns
  @column()
  declare account: string
  @column()
  declare amountMinor: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare direction: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare memo: string | null
  @column()
  declare orderId: number | null
  @column()
  declare transactionId: string
  @column()
  declare walletUserId: number | null
}

export class ManufacturerFinishingSchema extends BaseModel {
  static $columns = ['finishingOptionId', 'id', 'manufacturerProfileId'] as const
  $columns = ManufacturerFinishingSchema.$columns
  @column()
  declare finishingOptionId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare manufacturerProfileId: number
}

export class ManufacturerProfileSchema extends BaseModel {
  static $columns = ['city', 'country', 'createdAt', 'ibanEnc', 'id', 'isCorporate', 'publicAlias', 'score', 'status', 'taxIdEnc', 'trustTier', 'trustTierLocked', 'updatedAt', 'userId'] as const
  $columns = ManufacturerProfileSchema.$columns
  @column()
  declare city: string | null
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare ibanEnc: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCorporate: boolean
  @column()
  declare publicAlias: string
  @column()
  declare score: number
  @column()
  declare status: string
  @column()
  declare taxIdEnc: string | null
  @column()
  declare trustTier: number
  @column()
  declare trustTierLocked: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class MarketingEventSchema extends BaseModel {
  static $columns = ['campaign', 'createdAt', 'id', 'medium', 'name', 'path', 'source'] as const
  $columns = MarketingEventSchema.$columns
  @column()
  declare campaign: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare medium: string | null
  @column()
  declare name: string
  @column()
  declare path: string | null
  @column()
  declare source: string | null
}

export class MatchOfferSchema extends BaseModel {
  static $columns = ['adminOverride', 'createdAt', 'expiresAt', 'id', 'isExploration', 'manufacturerProfileId', 'orderId', 'printerId', 'respondedAt', 'round', 'score', 'slotDate', 'status', 'updatedAt'] as const
  $columns = MatchOfferSchema.$columns
  @column()
  declare adminOverride: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isExploration: boolean
  @column()
  declare manufacturerProfileId: number
  @column()
  declare orderId: number
  @column()
  declare printerId: number | null
  @column.dateTime()
  declare respondedAt: DateTime | null
  @column()
  declare round: number
  @column()
  declare score: number
  @column.date()
  declare slotDate: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MaterialSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'isActive', 'name', 'technology', 'updatedAt'] as const
  $columns = MaterialSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare technology: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ModelFileSchema extends BaseModel {
  static $columns = ['analysisError', 'analysisStatus', 'bboxXMm', 'bboxYMm', 'bboxZMm', 'blockedAt', 'blockedReason', 'createdAt', 'dfmIssues', 'format', 'id', 'isPrintable', 'originalName', 'ownerId', 'previousFileId', 'revision', 'sha256', 'sizeBytes', 'storageKey', 'triangleCount', 'updatedAt', 'volumeMm3'] as const
  $columns = ModelFileSchema.$columns
  @column()
  declare analysisError: string | null
  @column()
  declare analysisStatus: string
  @column()
  declare bboxXMm: number | null
  @column()
  declare bboxYMm: number | null
  @column()
  declare bboxZMm: number | null
  @column.dateTime()
  declare blockedAt: DateTime | null
  @column()
  declare blockedReason: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dfmIssues: any
  @column()
  declare format: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPrintable: boolean | null
  @column()
  declare originalName: string
  @column()
  declare ownerId: number
  @column()
  declare previousFileId: number | null
  @column()
  declare revision: number
  @column()
  declare sha256: string
  @column()
  declare sizeBytes: bigint | number
  @column()
  declare storageKey: string
  @column()
  declare triangleCount: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare volumeMm3: number | null
}

export class NotificationPreferenceSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'type', 'updatedAt', 'userId'] as const
  $columns = NotificationPreferenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class NotificationSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'data', 'emailedAt', 'eventKey', 'id', 'readAt', 'title', 'type', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: any
  @column.dateTime()
  declare emailedAt: DateTime | null
  @column()
  declare eventKey: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare title: string
  @column()
  declare type: string
  @column()
  declare userId: number
}

export class OrderItemSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'estGrams', 'estPrintMinutes', 'finishingCode', 'finishingColour', 'finishingMinor', 'finishingName', 'id', 'manufacturerShareMinor', 'material', 'modelFileId', 'orderId', 'printProfileId', 'quantity', 'scalePercent', 'technology', 'unitCostMinor', 'updatedAt'] as const
  $columns = OrderItemSchema.$columns
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare estGrams: number
  @column()
  declare estPrintMinutes: number
  @column()
  declare finishingCode: string | null
  @column()
  declare finishingColour: string | null
  @column()
  declare finishingMinor: number
  @column()
  declare finishingName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare manufacturerShareMinor: number
  @column()
  declare material: string
  @column()
  declare modelFileId: number
  @column()
  declare orderId: number
  @column()
  declare printProfileId: number | null
  @column()
  declare quantity: number
  @column()
  declare scalePercent: number
  @column()
  declare technology: string
  @column()
  declare unitCostMinor: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderMessageSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'maskedCount', 'orderId', 'originalEnc', 'readAt', 'senderId', 'senderRole'] as const
  $columns = OrderMessageSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maskedCount: number
  @column()
  declare orderId: number
  @column()
  declare originalEnc: string | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare senderId: number
  @column()
  declare senderRole: string
}

export class OrderSchema extends BaseModel {
  static $columns = ['baseTotalMinor', 'buyerId', 'channel', 'code', 'completedAt', 'createdAt', 'currency', 'deliveredAt', 'discountMinor', 'fxRateId', 'fxRateNano', 'id', 'matchingRound', 'platformFeeMinor', 'requiredTrustTier', 'sellerId', 'sellerShareMinor', 'shipCountry', 'shippingAddressEnc', 'shippingMinor', 'status', 'subtotalMinor', 'taxMinor', 'taxRateBps', 'totalMinor', 'updatedAt'] as const
  $columns = OrderSchema.$columns
  @column()
  declare baseTotalMinor: number
  @column()
  declare buyerId: number
  @column()
  declare channel: string
  @column()
  declare code: string
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare discountMinor: number
  @column()
  declare fxRateId: number | null
  @column()
  declare fxRateNano: bigint | number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare matchingRound: number
  @column()
  declare platformFeeMinor: number
  @column()
  declare requiredTrustTier: number
  @column()
  declare sellerId: number | null
  @column()
  declare sellerShareMinor: number
  @column()
  declare shipCountry: string
  @column()
  declare shippingAddressEnc: string | null
  @column()
  declare shippingMinor: number
  @column()
  declare status: string
  @column()
  declare subtotalMinor: number
  @column()
  declare taxMinor: number
  @column()
  declare taxRateBps: number
  @column()
  declare totalMinor: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PayeeTaxProfileSchema extends BaseModel {
  static $columns = ['addressEnc', 'beneficiaryId', 'beneficiaryType', 'createdAt', 'documentContentType', 'documentKey', 'ibanEnc', 'id', 'legalName', 'rejectionReason', 'reviewedAt', 'reviewedBy', 'status', 'submittedAt', 'taxNumberEnc', 'taxOffice', 'taxStatus', 'updatedAt', 'userId'] as const
  $columns = PayeeTaxProfileSchema.$columns
  @column()
  declare addressEnc: string
  @column()
  declare beneficiaryId: number
  @column()
  declare beneficiaryType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare documentContentType: string | null
  @column()
  declare documentKey: string | null
  @column()
  declare ibanEnc: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare legalName: string
  @column()
  declare rejectionReason: string | null
  @column.dateTime()
  declare reviewedAt: DateTime | null
  @column()
  declare reviewedBy: number | null
  @column()
  declare status: string
  @column.dateTime()
  declare submittedAt: DateTime
  @column()
  declare taxNumberEnc: string
  @column()
  declare taxOffice: string
  @column()
  declare taxStatus: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class PaymentProviderCallSchema extends BaseModel {
  static $columns = ['completedAt', 'createdAt', 'id', 'idempotencyKey', 'provider', 'resultRef'] as const
  $columns = PaymentProviderCallSchema.$columns
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idempotencyKey: string
  @column()
  declare provider: string
  @column()
  declare resultRef: string | null
}

export class PaymentSubMerchantSchema extends BaseModel {
  static $columns = ['beneficiaryId', 'beneficiaryType', 'createdAt', 'id', 'provider', 'subMerchantKey'] as const
  $columns = PaymentSubMerchantSchema.$columns
  @column()
  declare beneficiaryId: number
  @column()
  declare beneficiaryType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare provider: string
  @column()
  declare subMerchantKey: string
}

export class PaymentWebhookSchema extends BaseModel {
  static $columns = ['id', 'payload', 'processedAt', 'provider', 'providerEventId', 'receivedAt', 'type'] as const
  $columns = PaymentWebhookSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare payload: any
  @column.dateTime()
  declare processedAt: DateTime | null
  @column()
  declare provider: string
  @column()
  declare providerEventId: string
  @column.dateTime()
  declare receivedAt: DateTime
  @column()
  declare type: string
}

export class PaymentSchema extends BaseModel {
  static $columns = ['amountMinor', 'createdAt', 'currency', 'id', 'orderId', 'provider', 'providerRef', 'refundedMinor', 'status', 'updatedAt', 'walletUserId'] as const
  $columns = PaymentSchema.$columns
  @column()
  declare amountMinor: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number | null
  @column()
  declare provider: string
  @column()
  declare providerRef: string
  @column()
  declare refundedMinor: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare walletUserId: number | null
}

export class PayoutDocumentSchema extends BaseModel {
  static $columns = ['createdAt', 'currency', 'fileContentType', 'fileKey', 'grossMinor', 'id', 'issuedOn', 'kind', 'number', 'payoutId', 'rejectionReason', 'reviewedAt', 'reviewedBy', 'status', 'updatedAt', 'vatMinor', 'withholdingMinor'] as const
  $columns = PayoutDocumentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare fileContentType: string | null
  @column()
  declare fileKey: string | null
  @column()
  declare grossMinor: number
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare issuedOn: DateTime
  @column()
  declare kind: string
  @column()
  declare number: string
  @column()
  declare payoutId: number
  @column()
  declare rejectionReason: string | null
  @column.dateTime()
  declare reviewedAt: DateTime | null
  @column()
  declare reviewedBy: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vatMinor: number
  @column()
  declare withholdingMinor: number
}

export class PayoutSchema extends BaseModel {
  static $columns = ['amountMinor', 'beneficiaryId', 'beneficiaryType', 'createdAt', 'currency', 'grossMinor', 'id', 'orderId', 'paidAt', 'paidReference', 'providerRef', 'status', 'taxStatus', 'updatedAt', 'vatMinor', 'withholdingMinor'] as const
  $columns = PayoutSchema.$columns
  @column()
  declare amountMinor: number
  @column()
  declare beneficiaryId: number
  @column()
  declare beneficiaryType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare grossMinor: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number
  @column.dateTime()
  declare paidAt: DateTime | null
  @column()
  declare paidReference: string | null
  @column()
  declare providerRef: string | null
  @column()
  declare status: string
  @column()
  declare taxStatus: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vatMinor: number
  @column()
  declare withholdingMinor: number
}

export class PrintProfileSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'infillPercent', 'isActive', 'layerHeightMicron', 'name', 'postProcess', 'technology', 'timeFactorBps', 'updatedAt'] as const
  $columns = PrintProfileSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare infillPercent: number
  @column()
  declare isActive: boolean
  @column()
  declare layerHeightMicron: number
  @column()
  declare name: string
  @column()
  declare postProcess: string | null
  @column()
  declare technology: string
  @column()
  declare timeFactorBps: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PrinterMaterialSchema extends BaseModel {
  static $columns = ['colors', 'createdAt', 'currency', 'id', 'material', 'pricePerGramMinor', 'printerId', 'updatedAt'] as const
  $columns = PrinterMaterialSchema.$columns
  @column()
  declare colors: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare material: string
  @column()
  declare pricePerGramMinor: number
  @column()
  declare printerId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PrinterModelSchema extends BaseModel {
  static $columns = ['brand', 'buildVolumeXMm', 'buildVolumeYMm', 'buildVolumeZMm', 'createdAt', 'enclosed', 'id', 'model', 'technology', 'updatedAt'] as const
  $columns = PrinterModelSchema.$columns
  @column()
  declare brand: string
  @column()
  declare buildVolumeXMm: number
  @column()
  declare buildVolumeYMm: number
  @column()
  declare buildVolumeZMm: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enclosed: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare model: string
  @column()
  declare technology: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PrinterPrintProfileSchema extends BaseModel {
  static $columns = ['printProfileId', 'printerId'] as const
  $columns = PrinterPrintProfileSchema.$columns
  @column()
  declare printProfileId: number
  @column({ isPrimary: true })
  declare printerId: number
}

export class PrinterSchema extends BaseModel {
  static $columns = ['buildVolumeXMm', 'buildVolumeYMm', 'buildVolumeZMm', 'createdAt', 'id', 'isActive', 'manufacturerProfileId', 'name', 'printerModelId', 'technology', 'updatedAt'] as const
  $columns = PrinterSchema.$columns
  @column()
  declare buildVolumeXMm: number
  @column()
  declare buildVolumeYMm: number
  @column()
  declare buildVolumeZMm: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare manufacturerProfileId: number
  @column()
  declare name: string
  @column()
  declare printerModelId: number | null
  @column()
  declare technology: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductImageSchema extends BaseModel {
  static $columns = ['angle', 'contentType', 'createdAt', 'height', 'id', 'kind', 'modelFileId', 'qcPhotoId', 'renderVersion', 'reviewedAt', 'reviewedBy', 'status', 'storageKey', 'submittedBy', 'updatedAt', 'width'] as const
  $columns = ProductImageSchema.$columns
  @column()
  declare angle: number | null
  @column()
  declare contentType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare modelFileId: number
  @column()
  declare qcPhotoId: number | null
  @column()
  declare renderVersion: number | null
  @column.dateTime()
  declare reviewedAt: DateTime | null
  @column()
  declare reviewedBy: number | null
  @column()
  declare status: string
  @column()
  declare storageKey: string
  @column()
  declare submittedBy: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare width: number | null
}

export class ProductionJobSchema extends BaseModel {
  static $columns = ['acceptedAt', 'cancelReason', 'carrier', 'createdAt', 'dueAt', 'id', 'manufacturerProfileId', 'orderId', 'printerId', 'producedAt', 'rating', 'reviewComment', 'shippedAt', 'status', 'trackingNumber', 'updatedAt'] as const
  $columns = ProductionJobSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime
  @column()
  declare cancelReason: string | null
  @column()
  declare carrier: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare dueAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare manufacturerProfileId: number
  @column()
  declare orderId: number
  @column()
  declare printerId: number | null
  @column.dateTime()
  declare producedAt: DateTime | null
  @column()
  declare rating: number | null
  @column()
  declare reviewComment: string | null
  @column.dateTime()
  declare shippedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare trackingNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReferralSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'refereeCouponId', 'refereeId', 'referrerCouponId', 'referrerId', 'rejectReason', 'rewardedAt', 'status'] as const
  $columns = ReferralSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare refereeCouponId: number | null
  @column()
  declare refereeId: number
  @column()
  declare referrerCouponId: number | null
  @column()
  declare referrerId: number
  @column()
  declare rejectReason: string | null
  @column.dateTime()
  declare rewardedAt: DateTime | null
  @column()
  declare status: string
}

export class RfqBidSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'leadDays', 'manufacturerProfileId', 'note', 'rfqId', 'status', 'unitPriceMinor', 'updatedAt'] as const
  $columns = RfqBidSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leadDays: number
  @column()
  declare manufacturerProfileId: number
  @column()
  declare note: string | null
  @column()
  declare rfqId: number
  @column()
  declare status: string
  @column()
  declare unitPriceMinor: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RfqInviteSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isExploration', 'manufacturerProfileId', 'rfqId'] as const
  $columns = RfqInviteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isExploration: boolean
  @column()
  declare manufacturerProfileId: number
  @column()
  declare rfqId: number
}

export class RfqSchema extends BaseModel {
  static $columns = ['awardedBidId', 'bidsCloseAt', 'buyerId', 'code', 'color', 'createdAt', 'id', 'material', 'maxLeadDays', 'modelFileId', 'orderId', 'quantity', 'requiredTrustTier', 'shipCountry', 'status', 'technology', 'title', 'updatedAt'] as const
  $columns = RfqSchema.$columns
  @column()
  declare awardedBidId: number | null
  @column.dateTime()
  declare bidsCloseAt: DateTime
  @column()
  declare buyerId: number
  @column()
  declare code: string
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare material: string
  @column()
  declare maxLeadDays: number
  @column()
  declare modelFileId: number
  @column()
  declare orderId: number | null
  @column()
  declare quantity: number
  @column()
  declare requiredTrustTier: number
  @column()
  declare shipCountry: string
  @column()
  declare status: string
  @column()
  declare technology: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SellerProductSchema extends BaseModel {
  static $columns = ['catalogProductId', 'createdAt', 'currency', 'description', 'id', 'marginBps', 'minMakerTier', 'searchVector', 'sellerProfileId', 'status', 'title', 'updatedAt'] as const
  $columns = SellerProductSchema.$columns
  @column()
  declare catalogProductId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare marginBps: number
  @column()
  declare minMakerTier: number
  @column()
  declare searchVector: string | null
  @column()
  declare sellerProfileId: number
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SellerProfileSchema extends BaseModel {
  static $columns = ['brandMessage', 'brandName', 'businessName', 'createdAt', 'defaultMarginBps', 'id', 'isCorporate', 'logoContentType', 'logoKey', 'status', 'taxIdEnc', 'updatedAt', 'userId', 'walletAutoPay'] as const
  $columns = SellerProfileSchema.$columns
  @column()
  declare brandMessage: string | null
  @column()
  declare brandName: string | null
  @column()
  declare businessName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultMarginBps: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCorporate: boolean
  @column()
  declare logoContentType: string | null
  @column()
  declare logoKey: string | null
  @column()
  declare status: string
  @column()
  declare taxIdEnc: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
  @column()
  declare walletAutoPay: boolean
}

export class SettingSchema extends BaseModel {
  static $columns = ['createdAt', 'key', 'updatedAt', 'updatedBy', 'value'] as const
  $columns = SettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
  @column()
  declare value: any
}

export class ShippingRateSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'priceMinor', 'upToGrams', 'updatedAt', 'zoneId'] as const
  $columns = ShippingRateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare priceMinor: number
  @column()
  declare upToGrams: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare zoneId: number
}

export class ShippingZoneSchema extends BaseModel {
  static $columns = ['code', 'countries', 'createdAt', 'currency', 'extraPerKgMinor', 'id', 'isFallback', 'name', 'transitDaysMax', 'transitDaysMin', 'updatedAt'] as const
  $columns = ShippingZoneSchema.$columns
  @column()
  declare code: string
  @column()
  declare countries: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare extraPerKgMinor: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isFallback: boolean
  @column()
  declare name: string
  @column()
  declare transitDaysMax: number
  @column()
  declare transitDaysMin: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SliceEstimateSchema extends BaseModel {
  static $columns = ['contentHash', 'createdAt', 'error', 'gramsCenti', 'id', 'printMinutes', 'profileCode', 'slicer', 'status', 'supportGramsCenti'] as const
  $columns = SliceEstimateSchema.$columns
  @column()
  declare contentHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare error: string | null
  @column()
  declare gramsCenti: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare printMinutes: number | null
  @column()
  declare profileCode: string
  @column()
  declare slicer: string | null
  @column()
  declare status: string
  @column()
  declare supportGramsCenti: number | null
}

export class StoreConnectionSchema extends BaseModel {
  static $columns = ['accessTokenEnc', 'apiKeyEnc', 'apiSecretEnc', 'createdAt', 'currency', 'externalShopId', 'id', 'lastSyncedAt', 'ordersPolledAt', 'provider', 'refreshTokenEnc', 'sellerUserId', 'shopName', 'shopUrl', 'status', 'tokenExpiresAt', 'updatedAt', 'webhookSecretEnc'] as const
  $columns = StoreConnectionSchema.$columns
  @column()
  declare accessTokenEnc: string | null
  @column()
  declare apiKeyEnc: string | null
  @column()
  declare apiSecretEnc: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string | null
  @column()
  declare externalShopId: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastSyncedAt: DateTime | null
  @column.dateTime()
  declare ordersPolledAt: DateTime | null
  @column()
  declare provider: string
  @column()
  declare refreshTokenEnc: string | null
  @column()
  declare sellerUserId: number
  @column()
  declare shopName: string
  @column()
  declare shopUrl: string | null
  @column()
  declare status: string
  @column.dateTime()
  declare tokenExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare webhookSecretEnc: string | null
}

export class SupportRequestSchema extends BaseModel {
  static $columns = ['answeredAt', 'createdAt', 'email', 'id', 'message', 'orderCode', 'status', 'topic', 'userId'] as const
  $columns = SupportRequestSchema.$columns
  @column.dateTime()
  declare answeredAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string
  @column()
  declare orderCode: string | null
  @column()
  declare status: string
  @column()
  declare topic: string
  @column()
  declare userId: number | null
}

export class TaxRateSchema extends BaseModel {
  static $columns = ['country', 'createdAt', 'isActive', 'name', 'rateBps'] as const
  $columns = TaxRateSchema.$columns
  @column({ isPrimary: true })
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare rateBps: number
}

export class TwoFactorBackupCodeSchema extends BaseModel {
  static $columns = ['codeHash', 'createdAt', 'id', 'usedAt', 'userId'] as const
  $columns = TwoFactorBackupCodeSchema.$columns
  @column()
  declare codeHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'role', 'userId'] as const
  $columns = UserRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string
  @column()
  declare userId: number
}

export class UserSessionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'ipAddress', 'lastSeenAt', 'revokedAt', 'userAgent', 'userId'] as const
  $columns = UserSessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column.dateTime()
  declare lastSeenAt: DateTime
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'emailVerifiedAt', 'firstTouchCampaign', 'firstTouchMedium', 'firstTouchSource', 'fullName', 'id', 'locale', 'password', 'referralCode', 'suspendedAt', 'suspensionReason', 'twoFactorEnabledAt', 'twoFactorLastStep', 'twoFactorSecretEnc', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare firstTouchCampaign: string | null
  @column()
  declare firstTouchMedium: string | null
  @column()
  declare firstTouchSource: string | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare referralCode: string | null
  @column.dateTime()
  declare suspendedAt: DateTime | null
  @column()
  declare suspensionReason: string | null
  @column.dateTime()
  declare twoFactorEnabledAt: DateTime | null
  @column()
  declare twoFactorLastStep: bigint | number | null
  @column()
  declare twoFactorSecretEnc: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VerificationTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'token', 'type', 'usedAt', 'userId'] as const
  $columns = VerificationTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column()
  declare type: string
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number
}

export class WebhookDeliverySchema extends BaseModel {
  static $columns = ['attempts', 'createdAt', 'deliveredAt', 'endpointId', 'eventId', 'eventType', 'id', 'lastError', 'lastStatusCode', 'nextAttemptAt', 'payload', 'status'] as const
  $columns = WebhookDeliverySchema.$columns
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare endpointId: number
  @column()
  declare eventId: string
  @column()
  declare eventType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastError: string | null
  @column()
  declare lastStatusCode: number | null
  @column.dateTime()
  declare nextAttemptAt: DateTime
  @column()
  declare payload: any
  @column()
  declare status: string
}

export class WebhookEndpointSchema extends BaseModel {
  static $columns = ['consecutiveFailures', 'createdAt', 'disabledReason', 'id', 'isActive', 'secretEnc', 'url', 'userId'] as const
  $columns = WebhookEndpointSchema.$columns
  @column()
  declare consecutiveFailures: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare disabledReason: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare secretEnc: string
  @column()
  declare url: string
  @column()
  declare userId: number
}

export class WeeklyTemplateSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'printerId', 'schedule', 'updatedAt'] as const
  $columns = WeeklyTemplateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare printerId: number
  @column()
  declare schedule: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
