/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ManufacturerSchema extends BaseModel {
  static $columns = ['avgResponseMinutes', 'cancelledOrders', 'city', 'completedOrders', 'countryCode', 'createdAt', 'currencyCode', 'dailyCapacityGrams', 'displayName', 'hourlyRate', 'id', 'materials', 'maxBuildXMm', 'maxBuildYMm', 'maxBuildZMm', 'onTimeRate', 'pricePerGram', 'publicCode', 'qualityScore', 'status', 'stripeAccountId', 'updatedAt', 'userId'] as const
  $columns = ManufacturerSchema.$columns
  @column()
  declare avgResponseMinutes: number | null
  @column()
  declare cancelledOrders: number
  @column()
  declare city: string
  @column()
  declare completedOrders: number
  @column()
  declare countryCode: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currencyCode: string
  @column()
  declare dailyCapacityGrams: number
  @column()
  declare displayName: string
  @column()
  declare hourlyRate: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare materials: any
  @column()
  declare maxBuildXMm: number
  @column()
  declare maxBuildYMm: number
  @column()
  declare maxBuildZMm: number
  @column()
  declare onTimeRate: number | null
  @column()
  declare pricePerGram: number
  @column()
  declare publicCode: string
  @column()
  declare qualityScore: number | null
  @column()
  declare status: string
  @column()
  declare stripeAccountId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class MatchOfferSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'manufacturerId', 'productionRequestId', 'quotedPayout', 'respondedAt', 'score', 'scoreBreakdown', 'selectionReason', 'status', 'updatedAt'] as const
  $columns = MatchOfferSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare manufacturerId: number
  @column()
  declare productionRequestId: number
  @column()
  declare quotedPayout: number | null
  @column.dateTime()
  declare respondedAt: DateTime | null
  @column()
  declare score: number
  @column()
  declare scoreBreakdown: any
  @column()
  declare selectionReason: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OutboundWebhookEventSchema extends BaseModel {
  static $columns = ['attempts', 'createdAt', 'deliveredAt', 'id', 'lastError', 'nextAttemptAt', 'payload', 'productionRequestId', 'publicId', 'state', 'status', 'updatedAt'] as const
  $columns = OutboundWebhookEventSchema.$columns
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare nextAttemptAt: DateTime | null
  @column()
  declare payload: any
  @column()
  declare productionRequestId: number
  @column()
  declare publicId: string
  @column()
  declare state: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PayoutInstructionSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'currencyCode', 'id', 'manufacturerId', 'productionRequestId', 'publicId', 'sentAt', 'status', 'updatedAt'] as const
  $columns = PayoutInstructionSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currencyCode: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare manufacturerId: number
  @column()
  declare productionRequestId: number
  @column()
  declare publicId: string
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductionRequestSchema extends BaseModel {
  static $columns = ['acceptedAt', 'buyerCity', 'buyerCountry', 'color', 'createdAt', 'currencyCode', 'deliveredAt', 'designReference', 'id', 'manufacturerId', 'manufacturerPayout', 'matchAttempts', 'material', 'printEstimate', 'productionPhotos', 'publicId', 'quantity', 'requestedDeliveryBy', 'shippedAt', 'sistemALineItemRef', 'sistemAOrderRef', 'status', 'trackingNumber', 'updatedAt'] as const
  $columns = ProductionRequestSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column()
  declare buyerCity: string | null
  @column()
  declare buyerCountry: string
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currencyCode: string
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare designReference: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare manufacturerId: number | null
  @column()
  declare manufacturerPayout: number | null
  @column()
  declare matchAttempts: number
  @column()
  declare material: string
  @column()
  declare printEstimate: any | null
  @column()
  declare productionPhotos: any | null
  @column()
  declare publicId: string
  @column()
  declare quantity: number
  @column.date()
  declare requestedDeliveryBy: DateTime
  @column.dateTime()
  declare shippedAt: DateTime | null
  @column()
  declare sistemALineItemRef: string
  @column()
  declare sistemAOrderRef: string
  @column()
  declare status: string
  @column()
  declare trackingNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
