/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
import type DisputeTransformer from '#transformers/dispute_transformer'
import type InvoiceTransformer from '#transformers/invoice_transformer'
import type ManufacturerPublicTransformer from '#transformers/manufacturer_public_transformer'
import type MatchOfferTransformer from '#transformers/match_offer_transformer'
import type OrderTransformer from '#transformers/order_transformer'
import type PayeeTaxProfileTransformer from '#transformers/payee_tax_profile_transformer'
import type PayoutTransformer from '#transformers/payout_transformer'
import type PricingRegionTransformer from '#transformers/pricing_region_transformer'
import type ProductionJobTransformer from '#transformers/production_job_transformer'
import type RfqTransformer from '#transformers/rfq_transformer'
import type SellerProductCardTransformer from '#transformers/seller_product_card_transformer'
import type SellerProductTransformer from '#transformers/seller_product_transformer'
import type StoreTransformer from '#transformers/store_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Dispute = InferData<DisputeTransformer>
  export namespace Dispute {
    export type Variants = InferVariants<DisputeTransformer>
  }
  export type Invoice = InferData<InvoiceTransformer>
  export namespace Invoice {
    export type Variants = InferVariants<InvoiceTransformer>
  }
  export type ManufacturerPublic = InferData<ManufacturerPublicTransformer>
  export namespace ManufacturerPublic {
    export type Variants = InferVariants<ManufacturerPublicTransformer>
  }
  export type MatchOffer = InferData<MatchOfferTransformer>
  export namespace MatchOffer {
    export type Variants = InferVariants<MatchOfferTransformer>
  }
  export type Order = InferData<OrderTransformer>
  export namespace Order {
    export type Variants = InferVariants<OrderTransformer>
  }
  export type PayeeTaxProfile = InferData<PayeeTaxProfileTransformer>
  export namespace PayeeTaxProfile {
    export type Variants = InferVariants<PayeeTaxProfileTransformer>
  }
  export type Payout = InferData<PayoutTransformer>
  export namespace Payout {
    export type Variants = InferVariants<PayoutTransformer>
  }
  export type PricingRegion = InferData<PricingRegionTransformer>
  export namespace PricingRegion {
    export type Variants = InferVariants<PricingRegionTransformer>
  }
  export type ProductionJob = InferData<ProductionJobTransformer>
  export namespace ProductionJob {
    export type Variants = InferVariants<ProductionJobTransformer>
  }
  export type Rfq = InferData<RfqTransformer>
  export namespace Rfq {
    export type Variants = InferVariants<RfqTransformer>
  }
  export type SellerProductCard = InferData<SellerProductCardTransformer>
  export namespace SellerProductCard {
    export type Variants = InferVariants<SellerProductCardTransformer>
  }
  export type SellerProduct = InferData<SellerProductTransformer>
  export namespace SellerProduct {
    export type Variants = InferVariants<SellerProductTransformer>
  }
  export type Store = InferData<StoreTransformer>
  export namespace Store {
    export type Variants = InferVariants<StoreTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
